USE pokemon_unite;

INSERT INTO BoostEmblem(name, color1, color2, emblemtier, attrib1type, attrib1val, attrib2type, attrib2val) VALUES
("Beedrill", 'Black', 'Green', 'Bronze', 'HP', -30, 'SpD', 3),
("Beedrill", 'Black', 'Green', 'Silver', 'HP', -40, 'SpD', 4),
("Beedrill", 'Black', 'Green', 'Gold', 'HP', -50, 'SpD', 5),
("Blastoise", 'Blue', NULL, 'Bronze', 'SpA', 1.8, 'CDR', -0.3),
("Blastoise", 'Blue', NULL, 'Silver', 'SpA', 2.4, 'CDR', -0.5),
("Blastoise", 'Blue', NULL, 'Gold', 'SpA', 3, 'CDR', -0.6),
("Bulbasaur", 'Green', NULL, 'Bronze', 'HP', -30, 'SpA', 1.8),
("Bulbasaur", 'Green', NULL, 'Silver', 'HP', -40, 'SpA', 2.4),
("Bulbasaur", 'Green', NULL, 'Gold', 'HP', -50, 'SpA', 3),
("Caterpie", 'Green', NULL, 'Bronze', 'HP', -30, 'DEF', 3),
("Caterpie", 'Green', NULL, 'Silver', 'HP', -40, 'DEF', 4),
("Caterpie", 'Green', NULL, 'Gold', 'HP', -50, 'DEF', 5),
("Charmeleon", 'Red', NULL, 'Bronze', 'HP', 30, 'SpD', -3),
("Charmeleon", 'Red', NULL, 'Silver', 'HP', 40, 'SpD', -4),
("Charmeleon", 'Red', NULL, 'Gold', 'HP', 50, 'SpD', -5),
("Clefairy", 'Pink', NULL, 'Bronze', 'HP', 30, 'DEF', -3),
("Clefairy", 'Pink', NULL, 'Silver', 'HP', 40, 'DEF', -4),
("Clefairy", 'Pink', NULL, 'Gold', 'HP', 50, 'DEF', -5),
("Jigglypuff", 'Pink', NULL, 'Bronze', 'HP', 30, 'SpD', -3),
("Jigglypuff", 'Pink', NULL, 'Silver', 'HP', 40, 'SpD', -4),
("Jigglypuff", 'Pink', NULL, 'Gold', 'HP', 50, 'SpD', -5),
("Pidgeot", 'Yellow', NULL, 'Bronze', 'HP', 30, 'SpA', -1.8),
("Pidgeot", 'Yellow', NULL, 'Silver', 'HP', 40, 'SpA', -2.4),
("Pidgeot", 'Yellow', NULL, 'Gold', 'HP', 50, 'SpA', -3.0),
("Pikachu", 'White', NULL, 'Bronze', 'SpD', 3, 'CDR', -0.3),
("Pikachu", 'White', NULL, 'Silver', 'SpD', 4, 'CDR', -0.4),
("Pikachu", 'White', NULL, 'Gold', 'SpD', 5, 'CDR', -0.5),
("Rattata", 'White', NULL, 'Bronze', 'HP', -30, 'DEF', 3),
("Rattata", 'White', NULL, 'Silver', 'HP', -40, 'DEF', 4),
("Rattata", 'White', NULL, 'Gold', 'HP', -50, 'DEF', 5)